services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/mnt/config
    command:
      - -config.file=/mnt/config/config.yaml
  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./promtail:/mnt/config
      - nginx-logs:/var/log/nginx
    command:
      - -config.file=/mnt/config/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    depends_on:
      - prometheus
      - loki
  weather-api:
    image: weather-api
    build:
      context: ./api
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    container_name: weather-api
    expose:
      - "5000"
    depends_on:
      - prometheus
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - weather-api

volumes:
  grafana_storage: { }
  prometheus-data: { }
  nginx-logs: { }
